FROM ubuntu

RUN apt-get update && apt-get install -y openssh-server openjdk--jdk wget


RUN wget -r --no-parent --accept hadoop-3.?.?.tar.gz  https://apache.website-solution.net/hadoop/common/current && \
    tar -xzvf hadoop-3.?.?.tar.gz && \
    mv hadoop-3.?.? /usr/local/hadoop && \
    rm hadoop-3.?.?.tar.gz
